export default {
  HOME_SCREEN: 'HOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  ADD_EXPENSE_SCREEN: 'ADD_EXPENSE_SCREEN',
  ADD_TRIP_SCREEN: 'ADD_TRIP_SCREEN',
  TRIP_EXPENSE_SCREEN: 'TRIP_EXPENSE_SCREEN',
  WELCOME_SCREEN: 'WELCOME_SCREEN',
};
